# Generated by Django 3.1.7 on 2021-03-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_city', to='rest_api.area'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
