# Generated by Django 3.1.7 on 2021-03-15 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20210315_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateagency',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.area'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.city'),
        ),
    ]
