# Generated by Django 3.1.7 on 2021-03-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20210315_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='area',
            name='average_property_price',
        ),
        migrations.RemoveField(
            model_name='area',
            name='nearby_agents',
        ),
        migrations.RemoveField(
            model_name='area',
            name='nearby_properties',
        ),
        migrations.RemoveField(
            model_name='area',
            name='nearby_schools',
        ),
        migrations.RemoveField(
            model_name='area',
            name='nearby_stations',
        ),
        migrations.RemoveField(
            model_name='city',
            name='agencies',
        ),
        migrations.RemoveField(
            model_name='realestateagency',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='realestateagency',
            name='properties',
        ),
    ]
