# Generated by Django 3.1.7 on 2021-03-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20210315_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='area',
        ),
        migrations.RemoveField(
            model_name='city',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='school',
            name='nearby_agents',
        ),
        migrations.RemoveField(
            model_name='school',
            name='nearby_properties',
        ),
        migrations.RemoveField(
            model_name='station',
            name='nearby_agents',
        ),
        migrations.RemoveField(
            model_name='station',
            name='nearby_properties',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_agents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_properties',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viewed_properties',
        ),
        migrations.AlterField(
            model_name='agent',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='rest_api.city'),
        ),
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='rest_api.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rest_api.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_properties', to='rest_api.school'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_stations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_properties', to='rest_api.station'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rest_api.propertytype'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rest_api.accountmanager'),
        ),
    ]
